tmr.alarm(0, 3000, tmr.ALARM_SINGLE, function()
    lcd = dofile("rgb_lcd.lua")()
    lcd:setup(2, 1) -- setup GPIO PIN for I2C
    lcd:begin(16, 2, 0)
    --lcd:setRGB(0, 255, 100)
    --lcd:setColorAll()
end)
tmr.alarm(1, 15000, tmr.ALARM_AUTO, function()
    _, t, h = dht.read(3)
    lcd:clear()
    lcd:home()
    lcd:print("Temperture: " .. t .. "")
    lcd:setCursor(0, 1)
    lcd:print("Humidity: " .. h .. "")
end)
