--i2c.setup(0, 2, 1, i2c.SLOW)
--lcd = dofile("rgb_lcd.lua")()
--lcd:begin(16, 2, 0)
--lcd:setRGB(0, 255, 100)
_, t, h = dht.read(3)
lcd:clear()
lcd:print("Temperture: " .. t .. "")
lcd:setCursor(0, 1)
lcd:print("Humidity: " .. h .. "")
